# Generated by Django 5.2.1 on 2025-05-16 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estate_agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, help_text='Ссылка на видео (YouTube, Vimeo и т.д.)', null=True, unique=True, verbose_name='Video')),
                ('logo', models.ImageField(blank=True, help_text='Логотип компании', null=True, unique=True, upload_to='company_logos/', verbose_name='Logo')),
                ('history', models.TextField(help_text='История компании', null=True, verbose_name='Logo')),
                ('requisites', models.TextField(help_text='Реквизиты компании', null=True, verbose_name='Requisites')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120)),
                ('answer', models.CharField(max_length=500)),
                ('answer_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Фото сотрудника', null=True, upload_to='employee_images/', verbose_name='Employee image')),
                ('phone_number', models.TextField(help_text='Телефон', validators=[django.core.validators.RegexValidator('^\\+375(:?33|29|25|44)\\d{7}$')], verbose_name='Phone number')),
                ('email', models.EmailField(help_text='Почта', max_length=254, unique=True, verbose_name='Email')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estate_agency.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estate_agency.typeofwork')),
            ],
        ),
    ]
