# Generated by Django 5.2.1 on 2025-05-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='name',
            field=models.CharField(default='name', help_text='Название компании', unique=True),
        ),
    ]
