# Generated by Django 5.2.1 on 2025-05-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0002_aboutcompany_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcompany',
            options={'verbose_name': 'About company', 'verbose_name_plural': 'About companies'},
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='history',
            field=models.TextField(help_text='История компании', null=True, verbose_name='History'),
        ),
    ]
