# Generated by Django 4.2.6 on 2025-05-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0003_alter_aboutcompany_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Contacts', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='name',
            field=models.CharField(default='name', help_text='Название компании', max_length=40, unique=True),
        ),
    ]
