# Generated by Django 5.2.1 on 2025-05-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manager', '0004_alter_contacts_options_remove_contacts_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='work_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
