# Generated by Django 4.2.6 on 2025-05-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Percent'), ('AMOUNT', 'Amount')], default='AMOUNT', help_text='Тип скидки (процент/фиксированная)', max_length=8),
        ),
    ]
