# Generated by Django 5.2.1 on 2025-05-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0002_alter_promocode_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('%', 'Percent'), ('$', 'Amount')], default='$', help_text='Тип скидки (процент/фиксированная)', max_length=8),
        ),
    ]
