# Generated by Django 5.2.1 on 2025-05-16 19:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Максимальный бюджет клиента', max_digits=12, null=True)),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP клиент')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о клиенте')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0, help_text='Рейтинг владельца от 0 до 5', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о владельце', null=True)),
                ('phone_number', models.TextField(help_text='Телефон', validators=[django.core.validators.RegexValidator('^\\+375(:?33|29|25|44)\\d{7}$')], verbose_name='Phone number')),
                ('preferred_contact_time', models.CharField(blank=True, help_text='Предпочтительное время связи', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RealtyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Пример: квартира, дом, офис', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Type name')),
                ('category', models.CharField(choices=[('RES', 'Жилая'), ('COM', 'Коммерческая'), ('LAND', 'Земельный участок'), ('OTH', 'Другое')], default='RES', max_length=4, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Вид работы', max_length=30, verbose_name='Work type name')),
                ('description', models.TextField(blank=True, help_text='Описание работы', null=True, verbose_name='Work description')),
            ],
        ),
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование недвижимости', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Realty name')),
                ('address', models.CharField(help_text='Адрес', max_length=100, verbose_name='Address')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в валюте', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('area', models.DecimalField(decimal_places=2, help_text='Общая площадь в м²', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('built_year', models.PositiveSmallIntegerField(blank=True, help_text='Год постройки', null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2025)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_agency.owner')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estate_agency.realtytype')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('SALE', 'Продажа'), ('RENT', 'Аренда'), ('EXCHANGE', 'Обмен')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'В процессе'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена'), ('SUSPENDED', 'Приостановлена')], default='DRAFT', max_length=10)),
                ('actual_end_date', models.DateField(blank=True, help_text='Фактическая дата завершения платежей', null=True, verbose_name='End of payment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='estate_agency.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estate_agency.owner')),
                ('realty', models.ForeignKey(help_text='Объект недвижимости', on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='estate_agency.realty')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='ФИО', max_length=80, verbose_name='Full name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estate_agency.user'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_experience', models.FloatField(blank=True, help_text='Трудовой опыт', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)], verbose_name='Work experience')),
                ('work_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='estate_agency.typeofwork')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estate_agency.user')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estate_agency.user'),
        ),
    ]
