# Generated by Django 5.2.1 on 2025-05-16 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Почта', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.TextField(blank=True, help_text='Телефон', null=True, validators=[django.core.validators.RegexValidator('^\\+375(:?33|29|25|44)\\d{7}$')], verbose_name='Phone number'),
        ),
    ]
