# Generated by Django 4.2.6 on 2025-05-17 11:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agency', '0002_remove_owner_phone_number_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realty',
            options={'verbose_name': 'Realty', 'verbose_name_plural': 'Realty'},
        ),
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.DateField(default=datetime.date(2000, 1, 1), help_text='Дата рождения', validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 5, 17)), django.core.validators.MinValueValidator(datetime.date(1900, 5, 17))], verbose_name='Birthday date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Рейтинг владельца от 0 до 10', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
