# Generated by Django 5.2.1 on 2025-05-17 21:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agency', '0003_alter_realty_options_user_birth_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, help_text='Фото сотрудника', null=True, upload_to='employee_images/', verbose_name='Employee image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.DateField(help_text='Дата рождения', validators=[django.core.validators.MaxValueValidator(datetime.date(2025, 5, 18)), django.core.validators.MinValueValidator(datetime.date(1900, 5, 18))], verbose_name='Birthday date'),
        ),
    ]
