# Generated by Django 5.2.1 on 2025-05-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agency', '0004_employee_image_alter_user_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='photo',
            field=models.ImageField(blank=True, help_text='Фото недвижимости', null=True, upload_to='realties/', verbose_name='Realty photo'),
        ),
    ]
