# Generated by Django 5.2.1 on 2025-05-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agency', '0006_user_is_customer_user_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='is_in_deal',
            field=models.BooleanField(default=False),
        ),
    ]
