# Generated by Django 5.2.1 on 2025-05-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_author'),
        ('estate_agency', '0008_remove_user_user_userprofile_alter_customer_user_and_more'),
        ('reviews', '0003_alter_review_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
