# Generated by Django 5.2.1 on 2025-05-16 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estate_agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок отзыва', max_length=60, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Review title')),
                ('content', models.TextField(blank=True, help_text='Содержание отзыва', null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Review content')),
                ('rate', models.FloatField(help_text='Оценка', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estate_agency.user')),
            ],
        ),
    ]
