# Generated by Django 5.2.1 on 2025-05-19 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agency', '0008_remove_user_user_userprofile_alter_customer_user_and_more'),
        ('reviews', '0002_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estate_agency.userprofile'),
        ),
    ]
