# Generated by Django 5.2.1 on 2025-05-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('estate_agency', '0002_remove_owner_phone_number_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(blank=True, to='estate_agency.user'),
        ),
    ]
