# Generated by Django 5.2.1 on 2025-05-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_author'),
        ('estate_agency', '0003_alter_realty_options_user_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to='estate_agency.user'),
        ),
    ]
