# Generated by Django 5.2.1 on 2025-05-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_author'),
        ('estate_agency', '0008_remove_user_user_userprofile_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to='estate_agency.userprofile'),
        ),
    ]
